spring:
  datasource:
    url: jdbc:mysql://localhost:3306/music?serverTimezone=Asia/Shanghai
    username: music
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8888
  tomcat:
    remote-ip-header: x-forward-for
    uri-encoding: UTF-8
    max-threads: 1000
    connection-timeout: 200
  max-http-header-size: 8096

# 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: ethen #JWT加解密使用的密钥
  expiration: 3600 #JWT的超期限时间(60*60*1)
  tokenHead: Bearer  #JWT负载中拿到开头
